ORIGINAL_COUNT = 7

id_palette = {
    0   : "Original 0",
    1   : "Original 1",
    2   : "Original 2",
    3   : "Original 3",
    4   : "Original 4",
    5   : "Original 5",
    6   : "Original 6",

    20  : "Aerith-HoxNorf-FF7",
    21  : "Ayla-CrumpledMedal-CT",
    22  : "Baram-PocoLoco-FF6",
    23  : "Barret-CtrlxZ-FF7",
    24  : "Bartz-HoxNorf-FF5",
    25  : "Berserker-Badass-FF5",
    26  : "Bird-JamesWhite89-FF6",
    27  : "Boco-JamesWhite89-FF5",
    28  : "Bomb-JamesWhite89-FF6",
    29  : "Bubble Dragon-Badass-BB",
    30  : "Cecil (Dark Knight)-MetroidQuest-EC",
    31  : "Cecil (Paladin)-MetroidQuest-EC",
    32  : "Chancellor-Zozma-FF6",
    33  : "Cid-HoxNorf-FF4",
    34  : "Cirno-HoxNorf-Touhou",
    35  : "Cloud-HoxNorf-FF7",
    36  : "Crono-Badass-CT",
    37  : "Devout-HoxNorf-FF",
    38  : "Edea-CtrlxZ-FF8",
    39  : "Edge-PocoLoco-FF4",
    40  : "Edward-SpoonyBard-FFRK",
    41  : "Edward-Zozma-FF4",
    42  : "Eiko-PocoLoco-FF9",
    43  : "Eiko-ScarabEnigma-FF9",
    44  : "Elarra-HoxNorf-FFRK",
    45  : "Exdeath-CtrlxZ-FF5",
    46  : "Faris (Summoner)-FEOK-FF5",
    47  : "Faris-HoxNorf-FF5",
    48  : "Fish-ScarabEnigma-FF6",
    49  : "Freya-HoxNorf-FF9",
    50  : "Frog-Badass-CT",
    51  : "Frog-MetroidQuest-EC",
    52  : "FuSoYa-FEOK-FF4",
    53  : "Galuf-HoxNorf-FF5",
    54  : "Gardevoir-LoneRedMage-Pokemon",
    55  : "Garnet-HoxNorf-FF9",
    56  : "Gau (Suit)-Zozma-FF6",
    57  : "General Leo (Full)-SpoonyBard-FF6",
    58  : "General Leo (Redone)-SpoonyBard-FF6",
    59  : "Gestahl-MetroidQuest-EC",
    60  : "Gilgamesh-Kugawattan-FF5",
    61  : "Golbez-FEOK-FF4",
    62  : "Iffy-HoxNorf-Neptunia",
    63  : "Impressario-LoneRedMage-FF6",
    64  : "Interceptor-JamesWhite89-FF6",
    65  : "Iris-HoxNorf-FF15",
    66  : "Jessie-HoxNorf-FF7",
    67  : "Kain-MetroidQuest-EC",
    68  : "Kain-SpoonyBard-FFRK",
    69  : "Katarin-Zozma-FF6",
    70  : "Kelgar-CtrlxZ-FF5",
    71  : "King Baron-JamesWhite89-FF4",
    72  : "Krile-HoxNorf-FF5",
    73  : "Laguna-PocoLoco-FF8",
    74  : "Lenna (White Mage)-HoxNorf-FF5",
    75  : "Lenna-HoxNorf-FF5",
    76  : "Lightning-FEOK-FF13",
    77  : "Magus-FEOK-CT",
    78  : "Magus-MetroidQuest-EC",
    79  : "Mini-JamesWhite89-FF",
    80  : "Mog-JamesWhite89-FF6E",
    81  : "Mystic Knight-CtrlxZ-FF5",
    82  : "Nepgear-HoxNorf-Neptunia",
    83  : "Neptune (Adult)-HoxNorf-Neptunia",
    84  : "Neptune-HoxNorf-Neptunia",
    85  : "Ninja-CtrlxZ-FF5",
    86  : "Onion Knight-FEOK-FF3",
    87  : "Palom-HoxNorf-FF4",
    88  : "Porom-HoxNorf-FF4",
    89  : "Quina-SpoonyBard-FFRK",
    90  : "Quistis-FEOK-FF8",
    91  : "Rachel-Zozma-FF6",
    92  : "Relm (Amano)-HoxNorf-FF6",
    93  : "Relm-MetroidQuest-EC",
    94  : "Reno-CtrlxZ-FF7",
    95  : "Robo-Badass-CT",
    96  : "Rosa-PocoLoco-FF4",
    97  : "Rydia (Child)-HoxNorf-FF4",
    98  : "Rydia-HoxNorf-FF4",
    99  : "Rydia-Zozma-FF4",
    100 : "Ryu (Dragon)-Badass-BOF",
    101 : "Ryu-Badass-BOF",
    102 : "Samurai-CtrlxZ-FF5",
    103 : "Schala-HoxNorf-CT",
    104 : "Sephiroth-CtrlxZ-FF7",
    105 : "Seymour-LoneRedMage-FF10",
    106 : "Shantotto-HoxNorf-FF11",
    107 : "Soldier-LoneRedMage-FF4",
    108 : "Steiner-FEOK-FF9",
    109 : "Tellah-FEOK-FF4",
    110 : "Terra (Amano Blond Cape)-JCollins-FF6",
    111 : "Terra (Amano Cape)-JCollins-FF6",
    112 : "Terra (Amano)-JCollins-FF6",
    113 : "Terra-MetroidQuest-EC",
    114 : "Tiny Moogle-Rjenyawd-FF",
    115 : "Tohka-HoxNorf-DAL",
    116 : "Tonberry-JamesWhite89-FF",
    117 : "Ultros-PocoLoco-FF6",
    118 : "Uni-HoxNorf-Neptunia",
    119 : "Vanille-FEOK-FF13",
    120 : "Vivi-PocoLoco-FF9",
    121 : "White Mage-Matthew50-FF",
    122 : "Yang-SApprentice-FF4",
    123 : "Yuffie-HoxNorf-FF7",
    124 : "Zack-CtrlxZ-FF7",
    125 : "Zidane-HoxNorf-FF9",
    126 : "Kuja-HoxNorf-FF9",
    127 : "Reimu-HoxNorf-Touhou",
    128 : "Ram-HoxNorf-Neptunia",
    129 : "Rom-HoxNorf-Neptunia",
    130 : "Umaro (Morph)-CDude-FF6",
    131 : "Sarisa-HoxNorf-FF5",
    132 : "Lilith-HoxNorf-Darkstalkers",
    133 : "Marisa-HoxNorf-Touhou",
    135 : "Rumia-HoxNorf-Touhou",
    134 : "Papyrus-LoneRedMage-Undertale",
    136 : "Sans-LoneRedMage-Undertale",
    137 : "Toadette-HoxNorf-Mario",
    138 : "Talim-HoxNorf-SC4",
    139 : "Katt-ATinySpook-BOF2",
    140 : "Steve-PheonixMMKC777-Minecraft",
    141 : "Tonberry King-CDude-FF",
    142 : "Banjo Kazooie-HoxNorf-BK",
    143 : "PajaMog-CDude-FF",
    144 : "GrimLocke-Taloswind-FF6",
    145 : "Emperor-HoxNorf-FF2",
    146 : "Chen-HoxNorf-Touhou",
    147 : "Selphie-HoxNorf-FF8",
    148 : "Sora-HoxNorf-KH",
}

def get_path(id_):
    import os

    if id_ < ORIGINAL_COUNT:
        subdir = "original"
    else:
        subdir = "custom"

    name = id_palette[id_]
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), subdir, name + ".pal")
