ORIGINAL_COUNT = 22

id_sprite = {
    0   : "Terra",
    1   : "Locke",
    2   : "Cyan",
    3   : "Shadow",
    4   : "Edgar",
    5   : "Sabin",
    6   : "Celes",
    7   : "Strago",
    8   : "Relm",
    9   : "Setzer",
    10  : "Mog",
    11  : "Gau",
    12  : "Gogo",
    13  : "Umaro",
    14  : "Soldier",
    15  : "Imp",
    16  : "General Leo",
    17  : "Banon-Duncan",
    18  : "Esper Terra",
    19  : "Merchant",
    20  : "Ghost",
    21  : "Kefka",

    30  : "Aerith-HoxNorf-FF7",
    31  : "Ayla-CrumpledMedal-CT",
    32  : "Baram-PocoLoco-FF6",
    33  : "Barret-CtrlxZ-FF7",
    34  : "Bartz-HoxNorf-FF5",
    35  : "Berserker-Badass-FF5",
    36  : "Bird-JamesWhite89-FF6",
    37  : "Boco-JamesWhite89-FF5",
    38  : "Bomb-JamesWhite89-FF6",
    39  : "Bubble Dragon-Badass-BB",
    40  : "Cecil (Dark Knight)-MetroidQuest-EC",
    41  : "Cecil (Paladin)-MetroidQuest-EC",
    42  : "Chancellor-Zozma-FF6",
    43  : "Cid-HoxNorf-FF4",
    44  : "Cirno-HoxNorf-Touhou",
    45  : "Cloud-HoxNorf-FF7",
    46  : "Crono (No Sword)-Badass-CT",
    47  : "Crono (Sword)-Badass-CT",
    48  : "Devout-HoxNorf-FF",
    49  : "Edea-CtrlxZ-FF8",
    50  : "Edge-PocoLoco-FF4",
    51  : "Edward-SpoonyBard-FFRK",
    52  : "Edward-Zozma-FF4",
    53  : "Eiko-PocoLoco-FF9",
    54  : "Eiko-ScarabEnigma-FF9",
    55  : "Elarra-HoxNorf-FFRK",
    56  : "Exdeath-CtrlxZ-FF5",
    57  : "Faris (Summoner)-FEOK-FF5",
    58  : "Faris-HoxNorf-FF5",
    59  : "Fish-ScarabEnigma-FF6",
    60  : "Freya-HoxNorf-FF9",
    61  : "Frog-Badass-CT",
    62  : "Frog-MetroidQuest-EC",
    63  : "FuSoYa-FEOK-FF4",
    64  : "Galuf-HoxNorf-FF5",
    65  : "Gardevoir-LoneRedMage-Pokemon",
    66  : "Garnet (Long Hair)-HoxNorf-FF9",
    67  : "Garnet (Short Hair)-HoxNorf-FF9",
    68  : "Gau (Suit)-Zozma-FF6",
    69  : "General Leo (Full)-SpoonyBard-FF6",
    70  : "General Leo (Redone)-SpoonyBard-FF6",
    71  : "Gestahl-MetroidQuest-EC",
    72  : "Gilgamesh-Kugawattan-FF5",
    73  : "Golbez-FEOK-FF4",
    74  : "Iffy-HoxNorf-Neptunia",
    75  : "Impressario-LoneRedMage-FF6",
    76  : "Interceptor-JamesWhite89-FF6",
    77  : "Iris-HoxNorf-FF15",
    78  : "Jessie-HoxNorf-FF7",
    79  : "Kain-MetroidQuest-EC",
    80  : "Kain-SpoonyBard-FFRK",
    81  : "Katarin-Zozma-FF6",
    82  : "Kelgar-CtrlxZ-FF5",
    83  : "King Baron-JamesWhite89-FF4",
    84  : "Krile-HoxNorf-FF5",
    85  : "Laguna-PocoLoco-FF8",
    86  : "Lenna (White Mage)-HoxNorf-FF5",
    87  : "Lenna-HoxNorf-FF5",
    88  : "Lightning-FEOK-FF13",
    89  : "Magus-FEOK-CT",
    90  : "Magus-MetroidQuest-EC",
    91  : "Mini-JamesWhite89-FF",
    92  : "Mog-JamesWhite89-FF6E",
    93  : "Mystic Knight-CtrlxZ-FF5",
    94  : "Nepgear-HoxNorf-Neptunia",
    95  : "Neptune (Adult)-HoxNorf-Neptunia",
    96  : "Neptune-HoxNorf-Neptunia",
    97  : "Ninja-CtrlxZ-FF5",
    98  : "Onion Knight-FEOK-FF3",
    99  : "Palom-HoxNorf-FF4",
    100 : "Porom-HoxNorf-FF4",
    101 : "Quina-SpoonyBard-FFRK",
    102 : "Quistis-FEOK-FF8",
    103 : "Rachel-Zozma-FF6",
    104 : "Relm (Amano)-HoxNorf-FF6",
    105 : "Relm-MetroidQuest-EC",
    106 : "Reno-CtrlxZ-FF7",
    107 : "Robo-Badass-CT",
    108 : "Rosa-PocoLoco-FF4",
    109 : "Rydia (Child)-HoxNorf-FF4",
    110 : "Rydia-HoxNorf-FF4",
    111 : "Rydia-Zozma-FF4",
    112 : "Ryu (Dragon)-Badass-BOF",
    113 : "Ryu-Badass-BOF",
    114 : "Samurai-CtrlxZ-FF5",
    115 : "Schala-HoxNorf-CT",
    116 : "Sephiroth-CtrlxZ-FF7",
    117 : "Seymour-LoneRedMage-FF10",
    118 : "Shantotto-HoxNorf-FF11",
    119 : "Soldier-LoneRedMage-FF4",
    120 : "Steiner-FEOK-FF9",
    121 : "Tellah-FEOK-FF4",
    122 : "Terra (Amano Blond Cape)-JCollins-FF6",
    123 : "Terra (Amano Cape)-JCollins-FF6",
    124 : "Terra (Amano)-JCollins-FF6",
    125 : "Terra-MetroidQuest-EC",
    126 : "Tiny Moogle-Rjenyawd-FF",
    127 : "Tohka-HoxNorf-DAL",
    128 : "Tonberry-JamesWhite89-FF",
    129 : "Ultros-PocoLoco-FF6",
    130 : "Uni-HoxNorf-Neptunia",
    131 : "Vanille-FEOK-FF13",
    132 : "Vivi-PocoLoco-FF9",
    133 : "White Mage-Matthew50-FF",
    134 : "Yang-SApprentice-FF4",
    135 : "Yuffie-HoxNorf-FF7",
    136 : "Zack-CtrlxZ-FF7",
    137 : "Zidane-HoxNorf-FF9",
    138 : "Kuja-HoxNorf-FF9",
    139 : "Reimu-HoxNorf-Touhou",
    140 : "Ram-HoxNorf-Neptunia",
    141 : "Rom-HoxNorf-Neptunia",
    142 : "Umaro (Morph)-CDude-FF6",
    143 : "Sarisa-HoxNorf-FF5",
    144 : "Lilith-HoxNorf-Darkstalkers",
    145 : "Marisa-HoxNorf-Touhou",
    147 : "Rumia-HoxNorf-Touhou",
    146 : "Papyrus-LoneRedMage-Undertale",
    148 : "Sans-LoneRedMage-Undertale",
    149 : "Toadette-HoxNorf-Mario",
    150 : "Talim-HoxNorf-SC4",
    151 : "Katt-ATinySpook-BOF2",
    152 : "Steve-PheonixMMKC777-Minecraft",
    153 : "Tonberry King-CDude-FF",
    154 : "Banjo Kazooie-HoxNorf-BK",
    155 : "PajaMog-CDude-FF",
    156 : "GrimLocke-Taloswind-FF6",
    157 : "Emperor-HoxNorf-FF2",
    158 : "Chen-HoxNorf-Touhou",
    159 : "Selphie-HoxNorf-FF8",
    160 : "Sora-HoxNorf-KH",
    
    200 : "Flandre-HoxNorf-Touhou",
    201 : "Porom-Devout-HoxNorf-FF4",
    202 : "Remilia-HoxNorf-Touhou",
    203 : "Reisen-HoxNorf-Touhou",
    204 : "Cid-doubledown-FF6",
    205 : "Golbez_TAY-HoxNorf-FF4",
    206 : "Palom_Magus-HoxNorf-FF4",
    207 : "Patchouli-HoxNorf-Touhou",
    208 : "Suwako-HoxNorf-Touhou",
    209 : "Eiko_Miko-ScarabEnigma-FF9",
    
    # FFT
    300 : "Alma-HoxNorf-FFT",
    301 : "Orlandeau-ctrlxz-FFT",
}

def get_path(id_):
    import os

    if id_ < ORIGINAL_COUNT:
        subdir = "original"
    else:
        subdir = "custom"

    name = id_sprite[id_]
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), subdir, name + ".bin")
